export const GET_USER_SUCCESS = "GET_USER_SUCCESS"
export const GET_USER_ERROR = "GET_USER_ERROR"
export const GET_USER_REQUEST = "GET_USER_REQUEST"

export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS"
export const CREATE_USER_ERROR = "CREATE_USER_ERROR"
export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST"

export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS"
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR"
export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST"